### ISSUE TITLE
[Feature Request] Handle ENV vars in Lambda functions

### ISSUE THREAD

**Issue by zfoster** [gpoitch/sammie#12]
I have a need for deploying lambda functions with ENV vars per alias. This can be accomplished using https://github.com/awslabs/aws-sam-cli#package-and-deploy-to-lambda however the environment variables must be explicitly declared (with values) inside of the `sam.json` or `sam.yaml` file.

Since Sammie uses the template _per env_ , i.e., adds `-${env}` to the stack name, I would need sammie to add these environment variables from a file on a per environment basis.

An idea is to detect `${env}.json` files at the same directory level as the SAM config file `sam.json`. Sammie can then write those ENV vars into the lambda functions specified in `sam.json` if a file with the same name as the ENV exists.

E.g.

When using `sammie deploy` with the ENV `staging`, if there exists a `staging.json` in the same directory, extract those key values and add them to the `EnvironmentVariables` section of the Lambda portion of `sam.json`

**Comment by gpoitch** [comment]
Another idea that could be more flexible is to have env specific templates that get deep merged into the base template.
E.g.: `sam-production.json`:
```json
{
  "Resources": {
    "MyAppFunction1": {
      "Properties": {
        "MemorySize": 1280,
        "Environment": {
          "Variables": {
            "ENV_VAR1": "prod-env-var1",
            "ENV_VAR1": "prod-env-var2"
          }
        }
      }
    }
  }
}
```

Would get merged into the base `sam.json` upon package/deploy. That way it can support multiple functions, different permissions, and you could also up the memory size or whatever else per env.

Could also add a cli command to generate this for you.

**Comment by zfoster** [comment]
Yeah, I was thinking about multiple functions per template. I like the idea of this more, still works if you have say 3 functions in `beta` and only 2 in `production` whereas the other solution does not. More a fan of your approach

**Comment by gpoitch** [comment]
Just finished moving some code around (separated the `package` step) which should make this easy to add.
